### ISSUE TITLE
please create a docker image or create installed for this 

### ISSUE THREAD

**Issue by invisiblecoder99** [Fenrirthviti/stream-site#15]
please create installer or docker image to test it

**Comment by Fenrirthviti** [comment]
Unfortunately, I do not use docker and have no intentions of creating a docker image.

I am currently working towards an installer that will help automate some of the steps, but chances are the process will remain fairly manual. As this setup is moderately complicated, I would prefer people to understand the setup rather than me having to troubleshoot issues with install scripts.

**Comment by quorn23** [comment]
Hope this won't open the issue again, but i wanted to ask if in the last 3 years maybe things changed and you started using Docker, as i was searching for a docker image of your project.

**Comment by Fenrirthviti** [comment]
Unfortunately, no. I don't know anything about docker or how to create an image. As this was just a hobby project, I haven't really had much time to put in to it.
