### ISSUE TITLE
P2P-Streaming?

### ISSUE THREAD

**Issue by Hoerli1337** [Fenrirthviti/stream-site#32]
Can you add a P2P-Streaming-Option?
Maby a checkbox for the administration, that the player use a P2P-Player.
The video.js supports P2P with Peer5 (https://www.peer5.com/).

With the free Plan, this great Tool can handel the traffic if you host the stream on a private pc.

If you can add a P2P-Player without Peer5 would be great :)

**Comment by Fenrirthviti** [comment]
The site does not use the HTML5 player, because rtmp playback is not supported there. This would not be possible without transcoding to HLS or DASH, and those introduce too much latency for my use cases so I have not put any work into it.

You are welcome to update for it and submit a PR for review.
